export const seedProducts = [

  // Electronics
  {
    id: 'p1',
    name: 'Wireless Noise-Cancelling Headphones',
    category: 'Electronics',
    subcategory: null,
    price: 129.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Headphones_1.jpg/960px-Headphones_1.jpg',
    description: 'Over-ear headphones with active noise cancellation and 30-hour battery life.',
    rating: 4.6,
    stock: 18,
  },
  {
    id: 'p2',
    name: 'Smart Fitness Watch',
    category: 'Electronics',
    subcategory: null,
    price: 89.5,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Samsung_Galaxy_Gear_in_cradle.jpg/960px-Samsung_Galaxy_Gear_in_cradle.jpg',
    description: 'Tracks heart rate, sleep, and workouts with a 7-day battery life.',
    rating: 4.3,
    stock: 24,
  },
  {
    id: 'p3',
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    subcategory: null,
    price: 45,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg/960px-JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg',
    description: 'Compact waterproof speaker with rich bass and 12-hour playtime.',
    rating: 4.4,
    stock: 32,
  },
  {
    id: 'p16',
    name: 'Mechanical Keyboard',
    category: 'Electronics',
    subcategory: null,
    price: 79.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Mechanical_keyboard_example.jpg',
    description: 'Tactile mechanical keyboard with RGB backlighting and hot-swappable switches.',
    rating: 4.6,
    stock: 22,
  },
  {
    id: 'p17',
    name: '27" 4K Monitor',
    category: 'Electronics',
    subcategory: null,
    price: 329,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Computer_monitor_screen_image_simulated.jpg/960px-Computer_monitor_screen_image_simulated.jpg',
    description: 'Ultra-sharp 4K IPS monitor with HDR support for work and gaming.',
    rating: 4.7,
    stock: 12,
  },
  {
    id: 'p18',
    name: 'Wireless Charging Pad',
    category: 'Electronics',
    subcategory: null,
    price: 24.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Inductive_charging_of_LG_smartphone_%282%29.jpg/960px-Inductive_charging_of_LG_smartphone_%282%29.jpg',
    description: 'Fast-charge any Qi-enabled phone with this sleek charging pad.',
    rating: 4.2,
    stock: 40,
  },
  {
    id: 'p19',
    name: '4K Action Camera',
    category: 'Electronics',
    subcategory: null,
    price: 159,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Sony_HDR_AS5_Action_Cam_2_%E2%80%94_Sven_Volkens.jpg/960px-Sony_HDR_AS5_Action_Cam_2_%E2%80%94_Sven_Volkens.jpg',
    description: 'Waterproof action camera with image stabilization, shoots 4K60.',
    rating: 4.5,
    stock: 16,
  },
  {
    id: 'p20',
    name: 'Smart Home Hub',
    category: 'Electronics',
    subcategory: null,
    price: 99.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/BT_Home_Hub.JPG/960px-BT_Home_Hub.JPG',
    description: 'Control lights, locks, and thermostats from a single hub.',
    rating: 4.3,
    stock: 20,
  },
  {
    id: 'p21',
    name: 'Wireless Gaming Mouse',
    category: 'Electronics',
    subcategory: null,
    price: 54.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/2023_Mysz_komputerowa_Logitech_G903_Lightspeed.jpg/960px-2023_Mysz_komputerowa_Logitech_G903_Lightspeed.jpg',
    description: 'Low-latency wireless mouse with adjustable DPI up to 16000.',
    rating: 4.6,
    stock: 28,
  },
  {
    id: 'p22',
    name: 'Adjustable Tablet Stand',
    category: 'Electronics',
    subcategory: null,
    price: 19.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Tablet_Stand.jpg',
    description: 'Foldable aluminum stand compatible with most tablets and phones.',
    rating: 4.1,
    stock: 45,
  },
  {
    id: 'p23',
    name: '7-in-1 USB-C Hub',
    category: 'Electronics',
    subcategory: null,
    price: 39.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/USB_Hub_Internals.jpg/960px-USB_Hub_Internals.jpg',
    description: 'Expand your laptop with HDMI, USB-A, SD card, and more.',
    rating: 4.4,
    stock: 33,
  },
  {
    id: 'p24',
    name: 'Wireless Noise-Cancelling Earbuds',
    category: 'Electronics',
    subcategory: null,
    price: 99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Headphones_on_white_background.jpg',
    description: 'True wireless earbuds with active noise cancellation and 24-hour case battery.',
    rating: 4.5,
    stock: 30,
  },
  {
    id: 'p25',
    name: '20000mAh Power Bank',
    category: 'Electronics',
    subcategory: null,
    price: 44.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Turbo_Akku_Vac_Easy_Home_VC_618WP_-_battery_pack-1376.jpg/960px-Turbo_Akku_Vac_Easy_Home_VC_618WP_-_battery_pack-1376.jpg',
    description: 'High-capacity power bank with fast charging for phones and tablets.',
    rating: 4.4,
    stock: 38,
  },

  // Men
  {
    id: 'p4',
    name: 'Men\'s Classic Denim Jacket',
    category: 'Men',
    subcategory: null,
    price: 59.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Jean_Jacket%2C_Red_Hair%2C_and_a_Short_Black_Floral_Romper_%2816964185858%29.jpg',
    description: 'A timeless denim jacket made from durable cotton twill.',
    rating: 4.2,
    stock: 15,
  },
  {
    id: 'p6',
    name: 'Men\'s Cotton Crew Neck T-Shirt',
    category: 'Men',
    subcategory: null,
    price: 19.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/T-shirt_%28drawing%29.jpg',
    description: 'Soft, breathable 100% cotton t-shirt, available in multiple colors.',
    rating: 4.1,
    stock: 50,
  },
  {
    id: 'p26',
    name: 'Men\'s Wool Blend Crewneck Sweater',
    category: 'Men',
    subcategory: null,
    price: 64.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Swiss_Army_Wool_Sweater_%2815695462777%29.jpg/960px-Swiss_Army_Wool_Sweater_%2815695462777%29.jpg',
    description: 'Warm wool-blend sweater with a classic crewneck fit.',
    rating: 4.4,
    stock: 18,
  },
  {
    id: 'p27',
    name: 'Men\'s Slim Fit Chino Pants',
    category: 'Men',
    subcategory: null,
    price: 49.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Chino_pants.jpg/960px-Chino_pants.jpg',
    description: 'Versatile slim-fit chinos made from stretch cotton twill.',
    rating: 4.3,
    stock: 25,
  },
  {
    id: 'p77',
    name: 'Men\'s Slim Fit Dress Shirt',
    category: 'Men',
    subcategory: null,
    price: 44.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Camisade_pu%C3%B1o_doble.jpg/960px-Camisade_pu%C3%B1o_doble.jpg',
    description: 'Wrinkle-resistant dress shirt with a tailored slim fit.',
    rating: 4.3,
    stock: 22,
  },
  {
    id: 'p29',
    name: 'Classic Baseball Cap',
    category: 'Men',
    subcategory: 'Accessories',
    price: 22.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Baseball-Cap-c.jpg',
    description: 'Adjustable cotton baseball cap, one size fits most.',
    rating: 4.2,
    stock: 50,
  },
  {
    id: 'p32',
    name: 'Cotton Crew Socks 3-Pack',
    category: 'Men',
    subcategory: 'Accessories',
    price: 14.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Socks-clinton.jpg',
    description: 'Breathable combed cotton socks, pack of three pairs.',
    rating: 4.3,
    stock: 60,
  },
  {
    id: 'p33',
    name: 'Silk Neck Tie',
    category: 'Men',
    subcategory: 'Accessories',
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Necktie_%28drawing%29.jpg',
    description: 'Handcrafted 100% silk necktie for formal occasions.',
    rating: 4.4,
    stock: 22,
  },
  {
    id: 'p76',
    name: 'Men\'s Leather Wallet',
    category: 'Men',
    subcategory: 'Accessories',
    price: 34.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Python_skin_wallet%2C_closed%2C_2015-03-18.jpg/960px-Python_skin_wallet%2C_closed%2C_2015-03-18.jpg',
    description: 'Slim bifold leather wallet with RFID-blocking card slots.',
    rating: 4.5,
    stock: 30,
  },
  {
    id: 'p78',
    name: 'Men\'s Analog Watch',
    category: 'Men',
    subcategory: 'Accessories',
    price: 89.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Montinari_Milano.jpg',
    description: 'Stainless steel analog watch with a leather strap.',
    rating: 4.6,
    stock: 16,
  },

  // Women
  {
    id: 'p5',
    name: 'Women\'s Running Shoes',
    category: 'Women',
    subcategory: null,
    price: 74.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/OutDoor_2018%2C_Friedrichshafen_%281X7A0305%29.jpg/960px-OutDoor_2018%2C_Friedrichshafen_%281X7A0305%29.jpg',
    description: 'Lightweight breathable running shoes with responsive cushioning.',
    rating: 4.7,
    stock: 20,
  },
  {
    id: 'p28',
    name: 'Women\'s Packable Rain Jacket',
    category: 'Women',
    subcategory: null,
    price: 69.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Yellow_Raincoat.jpg',
    description: 'Lightweight waterproof jacket that packs into its own pocket.',
    rating: 4.5,
    stock: 20,
  },
  {
    id: 'p31',
    name: 'Women\'s Leather Ankle Boots',
    category: 'Women',
    subcategory: null,
    price: 119,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Arcteryx_Aerios%2C_OutDoor_2018%2C_Friedrichshafen_%281X7A0377%29.jpg/960px-Arcteryx_Aerios%2C_OutDoor_2018%2C_Friedrichshafen_%281X7A0377%29.jpg',
    description: 'Genuine leather ankle boots with a durable rubber sole.',
    rating: 4.5,
    stock: 14,
  },
  {
    id: 'p79',
    name: 'Women\'s Yoga Leggings',
    category: 'Women',
    subcategory: null,
    price: 39.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Yoga_practitioners_bums_on_Bondi_Beach.jpg/960px-Yoga_practitioners_bums_on_Bondi_Beach.jpg',
    description: 'High-waisted, four-way stretch leggings for yoga and everyday wear.',
    rating: 4.6,
    stock: 35,
  },
  {
    id: 'p80',
    name: 'Floral Midi Dress',
    category: 'Women',
    subcategory: null,
    price: 54.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Summer_dress_%285634765615%29.jpg/960px-Summer_dress_%285634765615%29.jpg',
    description: 'Flowy floral-print midi dress, perfect for warm weather.',
    rating: 4.5,
    stock: 20,
  },
  {
    id: 'p30',
    name: 'Merino Wool Scarf',
    category: 'Women',
    subcategory: 'Accessories',
    price: 34.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Scarf_soft.jpg/960px-Scarf_soft.jpg',
    description: 'Soft merino wool scarf to keep you warm in style.',
    rating: 4.6,
    stock: 30,
  },
  {
    id: 'p34',
    name: 'Polarized Sunglasses',
    category: 'Women',
    subcategory: 'Accessories',
    price: 39.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/2008-07-27_Sunglasses.jpg/960px-2008-07-27_Sunglasses.jpg',
    description: 'UV400 polarized sunglasses with a lightweight frame.',
    rating: 4.5,
    stock: 35,
  },
  {
    id: 'p35',
    name: 'Canvas Tote Bag',
    category: 'Women',
    subcategory: 'Accessories',
    price: 27.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Wikipedia_tote_bag.JPG/960px-Wikipedia_tote_bag.JPG',
    description: 'Durable canvas tote bag, perfect for everyday errands.',
    rating: 4.3,
    stock: 40,
  },
  {
    id: 'p81',
    name: 'Leather Crossbody Bag',
    category: 'Women',
    subcategory: 'Accessories',
    price: 64.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/DKNY_SM_Flap_Crossbody_W_-_ADJ_Chain_Crossbody_R1513005_Kalbsleder_beige_%281%29_%2816701889051%29.jpg/960px-DKNY_SM_Flap_Crossbody_W_-_ADJ_Chain_Crossbody_R1513005_Kalbsleder_beige_%281%29_%2816701889051%29.jpg',
    description: 'Compact leather crossbody bag with an adjustable strap.',
    rating: 4.6,
    stock: 18,
  },
  {
    id: 'p82',
    name: 'Gold Hoop Earrings',
    category: 'Women',
    subcategory: 'Accessories',
    price: 24.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Gold_hoop_earrings_with_candy_rolls_by_ASQ.jpg/960px-Gold_hoop_earrings_with_candy_rolls_by_ASQ.jpg',
    description: '14k gold-plated hoop earrings, hypoallergenic.',
    rating: 4.7,
    stock: 40,
  },

  // Kids
  {
    id: 'p83',
    name: 'Kids\' Graphic T-Shirt',
    category: 'Kids',
    subcategory: null,
    price: 14.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/58/T-shirts.jpg',
    description: 'Soft cotton tee with a fun printed graphic, machine washable.',
    rating: 4.4,
    stock: 45,
  },
  {
    id: 'p84',
    name: 'Kids\' Denim Overalls',
    category: 'Kids',
    subcategory: null,
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Bib-brace.jpg',
    description: 'Durable denim overalls with adjustable straps.',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 'p85',
    name: 'Kids\' Rain Boots',
    category: 'Kids',
    subcategory: null,
    price: 22.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Wellies.jpg',
    description: 'Waterproof rain boots with a fun colorful print.',
    rating: 4.6,
    stock: 30,
  },
  {
    id: 'p86',
    name: 'Kids\' Winter Puffer Jacket',
    category: 'Kids',
    subcategory: null,
    price: 44.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Men%27s_black_PVC_down_jacket_02.jpg/960px-Men%27s_black_PVC_down_jacket_02.jpg',
    description: 'Warm, lightweight puffer jacket with a snug hood.',
    rating: 4.5,
    stock: 20,
  },
  {
    id: 'p87',
    name: 'Kids\' Superhero Pajama Set',
    category: 'Kids',
    subcategory: null,
    price: 19.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Cat%27s_Pajamas_1926_ad.jpg/960px-Cat%27s_Pajamas_1926_ad.jpg',
    description: 'Soft cotton pajama set with a superhero print.',
    rating: 4.7,
    stock: 35,
  },
  {
    id: 'p88',
    name: 'Kids\' Sneakers',
    category: 'Kids',
    subcategory: null,
    price: 34.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sneakers_.jpg/960px-Sneakers_.jpg',
    description: 'Lightweight, easy-velcro sneakers built for playground days.',
    rating: 4.5,
    stock: 28,
  },
  {
    id: 'p89',
    name: 'Kids\' Sun Hat',
    category: 'Kids',
    subcategory: null,
    price: 12.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Child_in_Sun_Hat%2C_Dubbo%2C_NSW_%2830827855784%29.jpg/960px-Child_in_Sun_Hat%2C_Dubbo%2C_NSW_%2830827855784%29.jpg',
    description: 'Wide-brim sun hat with UPF 50+ protection.',
    rating: 4.3,
    stock: 40,
  },
  {
    id: 'p90',
    name: 'Kids\' Backpack',
    category: 'Kids',
    subcategory: null,
    price: 27.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Plecak_Hiker_50_L_HiMountain.jpg/960px-Plecak_Hiker_50_L_HiMountain.jpg',
    description: 'Durable school backpack sized for smaller shoulders.',
    rating: 4.6,
    stock: 24,
  },
  {
    id: 'p91',
    name: 'Kids\' Leggings Set (2-Pack)',
    category: 'Kids',
    subcategory: null,
    price: 17.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Leggings_%28AM_1983.026-1%29.jpg/960px-Leggings_%28AM_1983.026-1%29.jpg',
    description: 'Stretchy, comfortable leggings, sold as a pack of two.',
    rating: 4.4,
    stock: 38,
  },
  {
    id: 'p92',
    name: 'Kids\' Fleece Hoodie',
    category: 'Kids',
    subcategory: null,
    price: 24.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Young_man_with_hoodie.jpg',
    description: 'Cozy fleece hoodie with a kangaroo pocket.',
    rating: 4.5,
    stock: 32,
  },

  // Home & Kitchen
  {
    id: 'p7',
    name: '12-Piece Non-Stick Cookware Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 149,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Cookware_set_with_removable_handle.jpg',
    description: 'Durable non-stick pots and pans set, dishwasher safe.',
    rating: 4.5,
    stock: 10,
  },
  {
    id: 'p8',
    name: 'Stainless Steel French Press',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 34.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Stainless_steel_french_press.png/960px-Stainless_steel_french_press.png',
    description: 'Brew rich, full-flavored coffee with this insulated French press.',
    rating: 4.4,
    stock: 27,
  },
  {
    id: 'p9',
    name: 'Scented Soy Candle Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 24.5,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Burning_3-wick_candle.jpg/960px-Burning_3-wick_candle.jpg',
    description: 'Set of 3 hand-poured soy candles in relaxing seasonal scents.',
    rating: 4.6,
    stock: 40,
  },
  {
    id: 'p36',
    name: 'Electric Kettle',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 39.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Electric_kettle_-_%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%87%D0%B0%D0%B9%D0%BD%D0%B8%D0%BA.JPG/960px-Electric_kettle_-_%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%87%D0%B0%D0%B9%D0%BD%D0%B8%D0%BA.JPG',
    description: '1.7L rapid-boil electric kettle with auto shut-off.',
    rating: 4.5,
    stock: 26,
  },
  {
    id: 'p37',
    name: 'Digital Air Fryer',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 89.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hamilton_Beach_Easy_Reach_Sure-Crisp_Toaster_Oven_-_02.jpg/960px-Hamilton_Beach_Easy_Reach_Sure-Crisp_Toaster_Oven_-_02.jpg',
    description: '5.5L air fryer for crispy, low-oil cooking.',
    rating: 4.7,
    stock: 16,
  },
  {
    id: 'p38',
    name: '6-Piece Knife Block Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 79,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Knife_rack.jpg/960px-Knife_rack.jpg',
    description: 'High-carbon stainless steel knives with a wooden storage block.',
    rating: 4.6,
    stock: 12,
  },
  {
    id: 'p39',
    name: 'Bamboo Cutting Board Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 32.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Chopping_Board.jpg/960px-Chopping_Board.jpg',
    description: 'Set of 3 eco-friendly bamboo cutting boards.',
    rating: 4.4,
    stock: 30,
  },
  {
    id: 'p40',
    name: '16-Piece Ceramic Dinnerware Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/02021_0172_Porcelain_dinnerware_sets_in_Galicia.jpg/960px-02021_0172_Porcelain_dinnerware_sets_in_Galicia.jpg',
    description: 'Chip-resistant ceramic dinnerware for 4, microwave safe.',
    rating: 4.5,
    stock: 10,
  },
  {
    id: 'p41',
    name: 'Memory Foam Pillow',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 44.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/HK_SW_Hollywood_Road_Police_HQ_Art_Demo_12-2009_bed_and_pillows_in_white.JPG/960px-HK_SW_Hollywood_Road_Police_HQ_Art_Demo_12-2009_bed_and_pillows_in_white.JPG',
    description: 'Contoured memory foam pillow for neck and back support.',
    rating: 4.3,
    stock: 24,
  },
  {
    id: 'p42',
    name: 'Cotton Bath Towel Set',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 49.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Towel_blue_decorativepattern_closeup.jpg/960px-Towel_blue_decorativepattern_closeup.jpg',
    description: 'Set of 4 plush, quick-dry 100% cotton bath towels.',
    rating: 4.6,
    stock: 28,
  },
  {
    id: 'p43',
    name: 'Essential Oil Diffuser',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Duftlampen.jpg/960px-Duftlampen.jpg',
    description: 'Ultrasonic diffuser with LED mood lighting and auto shut-off.',
    rating: 4.4,
    stock: 32,
  },
  {
    id: 'p44',
    name: 'Digital Kitchen Scale',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 18.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Kitchen_Scale_%284108662942%29.jpg/960px-Kitchen_Scale_%284108662942%29.jpg',
    description: 'Precise digital scale for baking and portion control.',
    rating: 4.5,
    stock: 38,
  },
  {
    id: 'p45',
    name: '10-Inch Cast Iron Skillet',
    category: 'Home & Kitchen',
    subcategory: null,
    price: 34.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cornbread_in_cast_iron_pan.jpg/960px-Cornbread_in_cast_iron_pan.jpg',
    description: 'Pre-seasoned cast iron skillet built to last generations.',
    rating: 4.7,
    stock: 20,
  },

  // Books
  {
    id: 'p10',
    name: 'The Midnight Library',
    category: 'Books',
    subcategory: null,
    price: 14.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Haruhiko_oyabu_hard_boiled_novel_%22Winchester_model_70%22_first_edition_book_cover.jpg/960px-Haruhiko_oyabu_hard_boiled_novel_%22Winchester_model_70%22_first_edition_book_cover.jpg',
    description: 'A bestselling novel about the choices that make up a life well lived.',
    rating: 4.8,
    stock: 60,
  },
  {
    id: 'p11',
    name: 'Atomic Habits',
    category: 'Books',
    subcategory: null,
    price: 16.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Paperbacks_%2835400967690%29.jpg/960px-Paperbacks_%2835400967690%29.jpg',
    description: 'A practical guide to building good habits and breaking bad ones.',
    rating: 4.9,
    stock: 55,
  },
  {
    id: 'p46',
    name: 'Sapiens: A Brief History of Humankind',
    category: 'Books',
    subcategory: null,
    price: 18.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Bodo_language_textbooks.jpg/960px-Bodo_language_textbooks.jpg',
    description: 'A sweeping narrative of how Homo sapiens came to dominate the world.',
    rating: 4.7,
    stock: 45,
  },
  {
    id: 'p47',
    name: 'The Silent Patient',
    category: 'Books',
    subcategory: null,
    price: 15.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Burton_Taylor_Divorce_His_Hers_1973.jpg',
    description: 'A gripping psychological thriller about a woman who won\'t speak.',
    rating: 4.6,
    stock: 40,
  },
  {
    id: 'p48',
    name: 'Educated: A Memoir',
    category: 'Books',
    subcategory: null,
    price: 16.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ole_Bull%2C_a_memoir_%281883%29_%2814797173663%29.jpg/960px-Ole_Bull%2C_a_memoir_%281883%29_%2814797173663%29.jpg',
    description: 'A powerful memoir about the transformative power of education.',
    rating: 4.8,
    stock: 38,
  },
  {
    id: 'p49',
    name: 'Deep Work',
    category: 'Books',
    subcategory: null,
    price: 17.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Hong_Kong_Central_Library_Central_Book_Stack_3.JPG',
    description: 'Rules for focused success in a distracted world.',
    rating: 4.6,
    stock: 35,
  },
  {
    id: 'p50',
    name: 'The Alchemist',
    category: 'Books',
    subcategory: null,
    price: 13.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Paperback-stack.png',
    description: 'A timeless fable about following your dreams.',
    rating: 4.7,
    stock: 50,
  },
  {
    id: 'p51',
    name: 'Project Hail Mary',
    category: 'Books',
    subcategory: null,
    price: 19.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Illustrations_in_science_fiction_07.jpg',
    description: 'A lone astronaut must save humanity in this gripping sci-fi novel.',
    rating: 4.9,
    stock: 30,
  },
  {
    id: 'p52',
    name: 'Thinking, Fast and Slow',
    category: 'Books',
    subcategory: null,
    price: 18.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Old_book_bindings.jpg/960px-Old_book_bindings.jpg',
    description: 'An exploration of the two systems that drive the way we think.',
    rating: 4.6,
    stock: 28,
  },
  {
    id: 'p53',
    name: 'Where the Crawdads Sing',
    category: 'Books',
    subcategory: null,
    price: 16.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Open_Book_Tahquitz.JPG/960px-Open_Book_Tahquitz.JPG',
    description: 'A haunting coming-of-age story and murder mystery.',
    rating: 4.8,
    stock: 42,
  },
  {
    id: 'p54',
    name: 'The Psychology of Money',
    category: 'Books',
    subcategory: null,
    price: 17.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Reading_on_an_e-book_reader_%28Unsplash%29.jpg/960px-Reading_on_an_e-book_reader_%28Unsplash%29.jpg',
    description: 'Timeless lessons on wealth, greed, and happiness.',
    rating: 4.7,
    stock: 33,
  },
  {
    id: 'p55',
    name: 'Dune',
    category: 'Books',
    subcategory: null,
    price: 14.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Bookshelf_Prunksaal_OeNB_Vienna_AT_matl00786ch.jpg/960px-Bookshelf_Prunksaal_OeNB_Vienna_AT_matl00786ch.jpg',
    description: 'The epic science fiction saga of politics, religion, and power.',
    rating: 4.8,
    stock: 25,
  },

  // Sports
  {
    id: 'p12',
    name: 'Yoga Mat with Carry Strap',
    category: 'Sports',
    subcategory: null,
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Yoga_mat.jpg/960px-Yoga_mat.jpg',
    description: 'Extra-thick non-slip yoga mat, lightweight and easy to carry.',
    rating: 4.5,
    stock: 35,
  },
  {
    id: 'p13',
    name: 'Adjustable Dumbbell Set',
    category: 'Sports',
    subcategory: null,
    price: 199,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Aluminium_Dumbbell.jpg/960px-Aluminium_Dumbbell.jpg',
    description: 'Space-saving adjustable dumbbells, 5 to 25 lbs per hand.',
    rating: 4.6,
    stock: 8,
  },
  {
    id: 'p56',
    name: 'Official Size Basketball',
    category: 'Sports',
    subcategory: null,
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Bouncing_ball_strobe_edit.jpg/960px-Bouncing_ball_strobe_edit.jpg',
    description: 'Indoor/outdoor basketball with superior grip and durability.',
    rating: 4.5,
    stock: 30,
  },
  {
    id: 'p57',
    name: 'Match Soccer Ball',
    category: 'Sports',
    subcategory: null,
    price: 24.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/U.S._Air_Force_Staff_Sgt._David_Wilson%2C_a_noncommissioned_officer_in_charge_of_training_with_the_376th_Expeditionary_Logistics_Squadron%2C_juggles_a_soccer_ball_at_the_Ozyornoe_School_in_Kyrgyzstan_Sept_120903-F-KX404-061.jpg/960px-thumbnail.jpg',
    description: 'FIFA-quality size 5 soccer ball for training and match play.',
    rating: 4.4,
    stock: 35,
  },
  {
    id: 'p58',
    name: 'Graphite Tennis Racket',
    category: 'Sports',
    subcategory: null,
    price: 89.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Tennis_Racket_and_Balls.jpg/960px-Tennis_Racket_and_Balls.jpg',
    description: 'Lightweight graphite racket for power and control.',
    rating: 4.5,
    stock: 15,
  },
  {
    id: 'p59',
    name: 'Beginner Golf Club Set',
    category: 'Sports',
    subcategory: null,
    price: 249,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Golf_clubs.jpg/960px-Golf_clubs.jpg',
    description: 'Complete golf club set for new players, right-handed.',
    rating: 4.4,
    stock: 8,
  },
  {
    id: 'p60',
    name: 'Road Cycling Helmet',
    category: 'Sports',
    subcategory: null,
    price: 54.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cycling_Amsterdam_03.jpg/960px-Cycling_Amsterdam_03.jpg',
    description: 'Aerodynamic, well-ventilated helmet with adjustable fit.',
    rating: 4.6,
    stock: 22,
  },
  {
    id: 'p61',
    name: 'Anti-Fog Swim Goggles',
    category: 'Sports',
    subcategory: null,
    price: 16.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Pool_Goggles_%28Unsplash%29.jpg/960px-Pool_Goggles_%28Unsplash%29.jpg',
    description: 'UV-protective, anti-fog swim goggles with adjustable strap.',
    rating: 4.3,
    stock: 40,
  },
  {
    id: 'p62',
    name: 'Training Boxing Gloves',
    category: 'Sports',
    subcategory: null,
    price: 39.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Boxing_gloves.jpg',
    description: 'Durable padded gloves for boxing and kickboxing training.',
    rating: 4.5,
    stock: 20,
  },
  {
    id: 'p63',
    name: 'Complete Skateboard',
    category: 'Sports',
    subcategory: null,
    price: 79.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Penny_Skateboard_at_a_skateboard_and_surfer_shop_in_Shibuya%2C_Tokyo.jpg',
    description: 'Ready-to-ride skateboard with a maple deck and smooth wheels.',
    rating: 4.4,
    stock: 18,
  },
  {
    id: 'p64',
    name: 'Speed Jump Rope',
    category: 'Sports',
    subcategory: null,
    price: 12.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Ghanaian_kid_%28skipping_rope%29_01.jpg/960px-Ghanaian_kid_%28skipping_rope%29_01.jpg',
    description: 'Adjustable steel cable jump rope for cardio and speed training.',
    rating: 4.3,
    stock: 55,
  },
  {
    id: 'p65',
    name: '4-Person Camping Tent',
    category: 'Sports',
    subcategory: null,
    price: 129,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Camping_tent_on_tarp.jpg/960px-Camping_tent_on_tarp.jpg',
    description: 'Weatherproof dome tent that sets up in minutes.',
    rating: 4.6,
    stock: 12,
  },

  // Beauty
  {
    id: 'p14',
    name: 'Vitamin C Serum',
    category: 'Beauty',
    subcategory: null,
    price: 22.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/EFTA00000488_-_Wooden_cabinet_displays_various_skincare_products_bottles_and_boxes_neatly_arranged_on_its_shelves.jpg',
    description: 'Brightening facial serum with vitamin C and hyaluronic acid.',
    rating: 4.4,
    stock: 45,
  },
  {
    id: 'p15',
    name: 'Natural Bristle Hair Brush',
    category: 'Beauty',
    subcategory: null,
    price: 15.5,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Conair-brush.jpg/960px-Conair-brush.jpg',
    description: 'Gently detangles and adds shine without static.',
    rating: 4.3,
    stock: 38,
  },
  {
    id: 'p66',
    name: 'Daily Moisturizing Face Cream',
    category: 'Beauty',
    subcategory: null,
    price: 19.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Face_Cream_-_CiudadEmergente_-_Nicolas_Torregiani_-_Lets_Risk_It.jpg/960px-Face_Cream_-_CiudadEmergente_-_Nicolas_Torregiani_-_Lets_Risk_It.jpg',
    description: 'Lightweight, non-greasy moisturizer for all-day hydration.',
    rating: 4.4,
    stock: 45,
  },
  {
    id: 'p67',
    name: 'Matte Lipstick Set',
    category: 'Beauty',
    subcategory: null,
    price: 26.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/DiorLippenstift.jpg/960px-DiorLippenstift.jpg',
    description: 'Long-wearing matte lipsticks in 6 versatile shades.',
    rating: 4.5,
    stock: 35,
  },
  {
    id: 'p68',
    name: 'Silicone Facial Cleansing Brush',
    category: 'Beauty',
    subcategory: null,
    price: 22.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Eyeshadow_Brushes_and_Eyeshadow_Palette_%28White_Background%29_-_50922168986.jpg/960px-Eyeshadow_Brushes_and_Eyeshadow_Palette_%28White_Background%29_-_50922168986.jpg',
    description: 'Gentle vibrating brush for deep pore cleansing.',
    rating: 4.3,
    stock: 30,
  },
  {
    id: 'p69',
    name: 'Eau de Parfum Spray',
    category: 'Beauty',
    subcategory: null,
    price: 54.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Perfume_set_from_Sovjetunio_cca_1965.jpg/960px-Perfume_set_from_Sovjetunio_cca_1965.jpg',
    description: 'A floral, long-lasting fragrance for everyday wear.',
    rating: 4.6,
    stock: 20,
  },
  {
    id: 'p70',
    name: '12-Piece Nail Polish Set',
    category: 'Beauty',
    subcategory: null,
    price: 24.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Zoya_Nail_Polish_Erin_Sally_and_Lauren.jpg',
    description: 'A curated set of long-lasting, chip-resistant nail polishes.',
    rating: 4.4,
    stock: 28,
  },
  {
    id: 'p71',
    name: 'Ionic Hair Dryer',
    category: 'Beauty',
    subcategory: null,
    price: 44.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hooded_dryer_for_hair_drying_at_hair_salon.jpeg/960px-Hooded_dryer_for_hair_drying_at_hair_salon.jpeg',
    description: 'Fast-drying ionic hair dryer that reduces frizz.',
    rating: 4.5,
    stock: 18,
  },
  {
    id: 'p72',
    name: '10-Piece Makeup Brush Set',
    category: 'Beauty',
    subcategory: null,
    price: 29.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Blush_-_A_selection_of_makeup_brushes.jpg/960px-Blush_-_A_selection_of_makeup_brushes.jpg',
    description: 'Soft synthetic bristle brushes for flawless makeup application.',
    rating: 4.6,
    stock: 32,
  },
  {
    id: 'p73',
    name: 'Hydrating Sheet Mask 10-Pack',
    category: 'Beauty',
    subcategory: null,
    price: 16.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Facial_mask.jpg/960px-Facial_mask.jpg',
    description: 'Deeply hydrating sheet masks for a radiant glow.',
    rating: 4.5,
    stock: 50,
  },
  {
    id: 'p74',
    name: 'Broad Spectrum Sunscreen SPF 50',
    category: 'Beauty',
    subcategory: null,
    price: 18.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Japanese_sunscreen.jpg/960px-Japanese_sunscreen.jpg',
    description: 'Lightweight, non-greasy sunscreen with broad spectrum protection.',
    rating: 4.6,
    stock: 40,
  },
  {
    id: 'p75',
    name: 'Rechargeable Electric Shaver',
    category: 'Beauty',
    subcategory: null,
    price: 59.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Philips_Series_7000_shaver_head.jpg/960px-Philips_Series_7000_shaver_head.jpg',
    description: 'Cordless electric shaver with a precision trimmer attachment.',
    rating: 4.4,
    stock: 24,
  },

  // Grocery
  {
    id: 'p93',
    name: 'Extra Virgin Olive Oil 1L',
    category: 'Grocery',
    subcategory: null,
    price: 12.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/2023_Oliwa_z_oliwek_Redoro.jpg/960px-2023_Oliwa_z_oliwek_Redoro.jpg',
    description: 'Cold-pressed extra virgin olive oil, imported.',
    rating: 4.6,
    stock: 60,
  },
  {
    id: 'p94',
    name: 'Organic Whole Wheat Bread',
    category: 'Grocery',
    subcategory: null,
    price: 4.49,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vegan_no-knead_whole_wheat_bread_loaf%2C_September_2010.jpg/960px-Vegan_no-knead_whole_wheat_bread_loaf%2C_September_2010.jpg',
    description: 'Freshly baked organic whole wheat loaf.',
    rating: 4.4,
    stock: 40,
  },
  {
    id: 'p95',
    name: 'Farm Fresh Eggs (Dozen)',
    category: 'Grocery',
    subcategory: null,
    price: 5.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Egg_cartons_with_chicken_eggs_01.jpg/960px-Egg_cartons_with_chicken_eggs_01.jpg',
    description: 'Grade A large eggs from free-range hens.',
    rating: 4.7,
    stock: 55,
  },
  {
    id: 'p96',
    name: 'Basmati Rice 5kg',
    category: 'Grocery',
    subcategory: null,
    price: 14.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Basmati_Rice_India%2C_raw.jpg/960px-Basmati_Rice_India%2C_raw.jpg',
    description: 'Aged, extra-long grain basmati rice.',
    rating: 4.8,
    stock: 35,
  },
  {
    id: 'p97',
    name: 'Whole Milk 1 Gallon',
    category: 'Grocery',
    subcategory: null,
    price: 4.29,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/960px-Glass_of_Milk_%2833657535532%29.jpg',
    description: 'Fresh pasteurized whole milk.',
    rating: 4.5,
    stock: 50,
  },
  {
    id: 'p98',
    name: 'Roasted Almond Butter',
    category: 'Grocery',
    subcategory: null,
    price: 9.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Tatsuno_Almond_butter_turst.JPG/960px-Tatsuno_Almond_butter_turst.JPG',
    description: 'Creamy roasted almond butter, no added sugar.',
    rating: 4.6,
    stock: 30,
  },
  {
    id: 'p99',
    name: 'Aged Cheddar Cheese Block',
    category: 'Grocery',
    subcategory: null,
    price: 7.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/White_cheddar_cheese.jpg/960px-White_cheddar_cheese.jpg',
    description: 'Sharp aged cheddar, aged 12 months.',
    rating: 4.7,
    stock: 28,
  },
  {
    id: 'p100',
    name: 'Organic Ground Coffee 12oz',
    category: 'Grocery',
    subcategory: null,
    price: 11.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Coffee_powdered.jpg/960px-Coffee_powdered.jpg',
    description: 'Medium roast organic ground coffee, fair trade.',
    rating: 4.6,
    stock: 42,
  },
  {
    id: 'p101',
    name: 'Penne Pasta 1kg',
    category: 'Grocery',
    subcategory: null,
    price: 3.49,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/960px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg',
    description: 'Durum wheat penne pasta.',
    rating: 4.5,
    stock: 70,
  },
  {
    id: 'p102',
    name: 'Raw Honey 500g',
    category: 'Grocery',
    subcategory: null,
    price: 8.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Honey_jar_%28411317929%29.jpg/960px-Honey_jar_%28411317929%29.jpg',
    description: 'Unfiltered raw honey, locally sourced.',
    rating: 4.8,
    stock: 33,
  },

  // Fruits
  {
    id: 'p103',
    name: 'Fresh Bananas (1 lb)',
    category: 'Fruits',
    subcategory: null,
    price: 0.69,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cavendish_banana_from_Maracaibo.jpg/960px-Cavendish_banana_from_Maracaibo.jpg',
    description: 'Ripe, ready-to-eat bananas.',
    rating: 4.5,
    stock: 100,
  },
  {
    id: 'p104',
    name: 'Honeycrisp Apples (1 lb)',
    category: 'Fruits',
    subcategory: null,
    price: 2.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/960px-Pink_lady_and_cross_section.jpg',
    description: 'Crisp, sweet-tart Honeycrisp apples.',
    rating: 4.7,
    stock: 65,
  },
  {
    id: 'p105',
    name: 'Navel Oranges (1 lb)',
    category: 'Fruits',
    subcategory: null,
    price: 1.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ambersweet_oranges.jpg/960px-Ambersweet_oranges.jpg',
    description: 'Juicy, seedless navel oranges.',
    rating: 4.6,
    stock: 70,
  },
  {
    id: 'p106',
    name: 'Seedless Red Grapes (1 lb)',
    category: 'Fruits',
    subcategory: null,
    price: 3.49,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Red_grapes_%281%29.jpg/960px-Red_grapes_%281%29.jpg',
    description: 'Sweet, crisp seedless red grapes.',
    rating: 4.6,
    stock: 45,
  },
  {
    id: 'p107',
    name: 'Ripe Avocados (Pack of 4)',
    category: 'Fruits',
    subcategory: null,
    price: 4.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Avocado11.jpg/960px-Avocado11.jpg',
    description: 'Ready-to-eat Hass avocados.',
    rating: 4.7,
    stock: 40,
  },
  {
    id: 'p108',
    name: 'Strawberries (1 lb Box)',
    category: 'Fruits',
    subcategory: null,
    price: 3.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Organic-strawberries_Canada.jpg/960px-Organic-strawberries_Canada.jpg',
    description: 'Sweet, juicy fresh strawberries.',
    rating: 4.8,
    stock: 38,
  },
  {
    id: 'p109',
    name: 'Blueberries (Pint)',
    category: 'Fruits',
    subcategory: null,
    price: 4.49,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Vaccinium_corymbosum_Beeren.jpg/960px-Vaccinium_corymbosum_Beeren.jpg',
    description: 'Plump, antioxidant-rich fresh blueberries.',
    rating: 4.7,
    stock: 36,
  },
  {
    id: 'p110',
    name: 'Fresh Pineapple',
    category: 'Fruits',
    subcategory: null,
    price: 3.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Ananas_comosus_Blanco2.458.jpg/960px-Ananas_comosus_Blanco2.458.jpg',
    description: 'Sweet, golden ripe whole pineapple.',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 'p111',
    name: 'Kiwi Fruit (Pack of 6)',
    category: 'Fruits',
    subcategory: null,
    price: 3.49,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kiwi_aka.jpg/960px-Kiwi_aka.jpg',
    description: 'Tangy-sweet, vitamin C-rich kiwi fruit.',
    rating: 4.5,
    stock: 42,
  },
  {
    id: 'p112',
    name: 'Mixed Citrus Box',
    category: 'Fruits',
    subcategory: null,
    price: 12.99,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Citrus_fruits.jpg/960px-Citrus_fruits.jpg',
    description: 'A mixed box of oranges, grapefruits, and lemons.',
    rating: 4.6,
    stock: 20,
  },
]
